### ISSUE TITLE
Possible bug in equality in dashboard

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#110]
@nnelissen  this is probably fine, but I noticed that in the dashboard there is: 

`if nr_scenarios <= 2:`

https://github.com/Urban-Analytics/RAMP-UA/blob/236b292fd46d59608b37b9797f182c42f076dcb4/microsim/dashboard.py#L1084

and then later

`if nr_scenarios >= 2:`

https://github.com/Urban-Analytics/RAMP-UA/blob/236b292fd46d59608b37b9797f182c42f076dcb4/microsim/dashboard.py#L1170

So if there are two scenarios _both_ conditions are true. Just checking that's the intended behaviour?

**Comment by nnelissen** [comment]
Yes, if nr_scenarios == 2, it should produce the usual dashboard.html (with the difference scores created eg https://github.com/Urban-Analytics/RAMP-UA/blob/236b292fd46d59608b37b9797f182c42f076dcb4/microsim/dashboard.py#L1034) as well as dashboard_scenarios.html. For 1 scenario, it only creates dashboard.html (no scenarios to compare), for 3 or more only dashboard_scenarios.html (no way to create an easy to interpret difference score between more than 2 scenarios).
