### ISSUE TITLE
Try to make dashboard activities/locations as generic as possible

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#112]
At some point we are going to add new activities/locations, so will need to add these to the dashboard. I'm not sure how much of this will be possible, but can you try to make the code as generic as possible? Ideally we would not need to manually add a new activity (e.g. 'Cinema') to the dashboard at all because it will be able to work out all the possible activities from the microsim model, but this is probably unrealistic. Instead, could you try to make it as easy as possible to add new activities that should be graphed or mapped, e.g. by maintaining a list or dictionary of activities that we can add to later if we want to add new activities. Don't worry if this is too difficult or would mean a huge change to the code. Clear comments might be enough.

**Comment by nnelissen** [comment]
Conditions and venues are each in a dictionary defined starting at https://github.com/Urban-Analytics/RAMP-UA/blob/4a60c3fe6883323b4ec4299e2a6d3be9c01cd6dc/microsim/dashboard.py#L850
The rest of the code cycles through these entries, so adding/deleting them there should be the only change required.

Exception is when danger values are calculated per MSOA at https://github.com/Urban-Analytics/RAMP-UA/blob/4a60c3fe6883323b4ec4299e2a6d3be9c01cd6dc/microsim/dashboard.py#L1048. I've restricted this to Retail, Primary and Secondary schools for now as Work doesn't make much sense when it's not a physical location (and Home is not a danger score one could act on). This can be updated when workplaces are introduced.

Currently this only works for Devon as the dashboard reads in the retail and school info in a given format. I'll write an alternative compatible with the UCL data.

**Comment by nnelissen** [comment]
UCL/QUANT compatible dashboard is now available as microsim/dashboard_QUANT.py. microsim/dashboard.py works with the devon_data as before. Currently in dev_NN, will do pull request next. @nickmalleson My computer crashes when I try the microsim with the QUANT data (out of memory) so I haven't been able to test it with 'real' microsim output.

dashboard_QUANT.py reads in QUANT data from the variable quant_dir (similar to how it's defined in microsim_model.py), you may have to change this if your data are located elsewhere.
`quant_dir = os.path.join(data_dir,"QUANT_RAMP","model-runs")`

You also need updated *Zones.csv files (with MSOA column):
The original QUANT *Zones.csv files only come with easting/northing coordinates of venue. I wrote a script to turn this into MSOAs (QUANT_RAMP/add_msoa_to_venue.py) and save in a new column. This has been done for England & Wales only at the moment (the other areas don't use MSOAs). Also, it's only done for primary and secondary schools, and retail (not hospitals). In other words, the 3 new files (to replace existing) are primaryZones.csv, secondaryZones.csv and retailZones.csv.
