### ISSUE TITLE
Add population file as a parameter

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#120]
Would it be possible to add the input population as a parameter? Thinking it might be useful for scenarios where we alter aspects of the population e.g. a healthier population.

**Comment by nickmalleson** [comment]
Good question @spoonerf . The short answer is 'yes' but there's a longer answer where we re-do the way that data are read into the model as part of the move to make it run across the whole country.

One question though: if we have multiple populations it means having multiple large csv files in the repo. Instead could we just add columns to the existing population file(s) that represented the new (health related) factors and have model parameters that set how the model should respond to those new columns?

**Comment by spoonerf** [comment]
That's a very good idea! Will do that instead.
