### ISSUE TITLE
Bug in QUANT-RAMP data dir

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#122]
Hi @nnelissen, I've added the QUANT_RAMP data to the repo but I think there  is an error in the microsim/QUANTRampAPI2.py file here:

https://github.com/Urban-Analytics/RAMP-UA/blob/d87139a7f737ac7c69bbcd1d0b11aec7ece4066e/microsim/QUANTRampAPI2.py#L32

At that line it sets the directory to start from a `data` directory but I've put the quant-ramp data with everything else in `devon_data`. I think that we need to do it this way because in microsim_model.py it assumes that the data are in `devon_data`, e.g.:

https://github.com/Urban-Analytics/RAMP-UA/blob/d87139a7f737ac7c69bbcd1d0b11aec7ece4066e/microsim/microsim_model.py#L786

Presumably you hard-coded the directory into `QUANTRampAPI2.py` for the dashboard? Anyway hard-coding it gives me this error when I run the model:

```
FileNotFoundError: [Errno 2] File data/QUANT_RAMP/model-runs/primaryPopulation.csv does not exist: 'data/QUANT_RAMP/model-runs/primaryPopulation.csv'
```

Possibly the best solution is to pass the root data directory to `QUANTRampAPI2.py` directly rather than hard code it, but I'm not sure so will leave it with you. Could you have a look at the `national_data` branch: https://github.com/Urban-Analytics/RAMP-UA/blob/national_data

**Comment by Sparrow0hawk** [comment]
@nickmalleson could you please let me know the steps you performed so I can attempt to replicate this error?

**Comment by nickmalleson** [comment]
@Sparrow0hawk all I need to do is checkout the `national_data` branch - that has the data and the new paramaeter to choose to use the national data (curently the default in that branch)

**Comment by nnelissen** [comment]
@nickmalleson I put it in /data on purpose as I thought we were going to remove devon-data (or keep it as demo). I'll add quantdir as a parameter. 
The QUANT data don't work with the dashboard yet, this is being fixed - https://github.com/Urban-Analytics/RAMP-UA/issues/112#issuecomment-686346462

**Comment by nnelissen** [comment]
@nickmalleson I think you fixed this in national_data so can be closed?
