### ISSUE TITLE
Creating a QUANTRampAPI class

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#123]
## Overview

The QUANT data is loaded through the [`QUANTRampAPI2.py`](https://github.com/Urban-Analytics/RAMP-UA/blob/national_data/microsim/QUANTRampAPI2.py) file, to better align this with our existing API a piece of work should be performed to convert this file into an object class which can be called from within `microsim_model.py` to manage data loading.

## Key ideas

- Managing the data directory under existing API

The following line hardcodes in the data directory. We want to avoid this sort of pattern in general and would be better handled by the class loading the data directory that is passed to our parameters file.
https://github.com/Urban-Analytics/RAMP-UA/blob/846514e95411dfa8faff15e37ff28c6aab68538d/microsim/QUANTRampAPI2.py#L32

- loading the data as class attributes
- run data processing steps within the class

## Psuedo code example

```python

class QuantRampAPI:
    """
    Class that handles integration of QUANT data into the RAMP microsim model
    """

    def __init__(self, data_dir):
        """
        Initialiser for QuantRampAPI
        
        :param data_dir: string, should be the data_dir parameter from Microsim, provides directory 
         path to data directory to use for model running
        """

        self.data_dir = data_dir

        # class the class methods for processing data in the init statement so 
        # returned class object contains all data ready to use
        self.open_data()
        
    @classmethod
    def open_data(self):
           """
           open_data function, reads in all data in provided data directory and creates series of class object attributes
           """
           self.example_data = pd.read_csv(os.path.join(data_dir, standard_filename.csv)

```

**Comment by nnelissen** [comment]
Added in https://github.com/Urban-Analytics/RAMP-UA/pull/135#issue-492537791
