### ISSUE TITLE
Error - No module named 'microsim'

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#124]
Hi all, 

This may be me making a mistake somewhere but I just pulled the latest master and am getting this error when running:

`Traceback` (most recent call last):
  File "microsim/microsim_model.py", line 22, in <module>
    from microsim.activity_location import ActivityLocation
ModuleNotFoundError: No module named 'microsim'`

Using the latest environment:

`conda activate ramp-ua
python3 microsim/microsim_model.py -p model_parameters/default.yml
`
Is anyone else having issues?

**Comment by nickmalleson** [comment]
Yes I have the same error, but weirdly not when I run the programme through my IDE. I think these were introduced in https://github.com/Urban-Analytics/RAMP-UA/issues/107, I'm looking now

**Comment by nickmalleson** [comment]
I've just rolled back issue https://github.com/Urban-Analytics/RAMP-UA/issues/107 with commit https://github.com/Urban-Analytics/RAMP-UA/commit/35829435edc0f7559ec07e29bad6056ce027128c and I think the imports are OK now. @spoonerf could you check? @nnelissen and @Sparrow0hawk we may need to re-fix this again as I may have now just re-broken whatever it was you were yrying to fix in https://github.com/Urban-Analytics/RAMP-UA/issues/107

**Comment by Sparrow0hawk** [comment]
With the changes in #107 have you activated your conda environments and run
```bash
cd RAMP-UA
conda activate ramp-ua
python setup.py develop
```

This is a critical step to ensure the python module is added to the `PYTHONPATH` in the environment to prevent these issues.

**Comment by nickmalleson** [comment]
Oh right, sorry I missed the need for `python setup.py develop`. @spoonerf if you've not brought in the new version of master yet could you try that? If it works I'll undo my most recent commit (https://github.com/Urban-Analytics/RAMP-UA/commit/55134b06f4ca4423a0356ba6c24389a54ab2ee29)

**Comment by nickmalleson** [comment]
Thanks @Sparrow0hawk you were right. I've undone the changes in commit https://github.com/Urban-Analytics/RAMP-UA/commit/b47d471199023ef08fa0e8e25a8a033f83845688 and it works OK for me now. @spoonerf let me know how you get on.

**Comment by Sparrow0hawk** [comment]
No problem, it's a first time only setup step whenever you have to create your `ramp-ua` environment so easy to miss but should resolve these issues.

**Comment by spoonerf** [comment]
Ah brilliant, all working now. Have created a PR to update the documentation in #125
