### ISSUE TITLE
msoa info

### ISSUE THREAD

**Issue by jabrams23** [Urban-Analytics/RAMP-UA#129]
@nickmalleson i am writing some new code for local outbreak scenarios. I want to simulate a local outbreak or super spreader event in one msoa that we can specify. do you currently pass the msoa to the r code? and if yes, what is the column called?

**Comment by nickmalleson** [comment]
@jabrams23 have a look in the `r_interface` file here:

https://github.com/Urban-Analytics/RAMP-UA/blob/4b8a03287b1dc0b5ad6099272779c48ef94d0268/microsim/r_interface.py#L50

That line shows you which columns extracted from the main table and passed to the R code. 'area' is the MSOA code, so yet that one ends up in the table that is passed to R
