### ISSUE TITLE
Add new commuting flows

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#139]

**Comment by nickmalleson** [comment]
@spoonerf @jabrams23 please could you try to run the code on the branch `nm-commuting`: https://github.com/Urban-Analytics/RAMP-UA/tree/nm-commuting ? I've implemented commuting to different locations based on census flows, but I'm getting an error (below). I've not tried to work out what's wrong yet, and it's probably because I don't have the latest version of the R code, but I'd like to know if it works for you anyway. I'm going to write some tests asap. Also at the moment everyone ends up with lots of possible work places (~30) but most have very low probability so I could cut that down to the top 5 or something. 


rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (file, local = FALSE, echo = verbose, print.eval = echo,  : 
  covid_run.R:54:49: unexpected ','
53:                        number_people_local=100,
54:                        local_prob_increase=0.75),
                                                    ^

**Comment by spoonerf** [comment]
Hi @nickmalleson I think it's a misplaced bracket after 0.75, it should just end with a comma.

**Comment by nickmalleson** [comment]
Finished https://github.com/Urban-Analytics/RAMP-UA/pull/141
