### ISSUE TITLE
Shorter auto-brancher branch names

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#155]
Hi @Sparrow0hawk I love the auto brancher, but is it possible to configure it to use only the first _x_ characters in the issue name? No big deal, it just means that branch names can become very long, e.g.: `nickmalleson-issue-154-_minor_save_workplaces_if_no-cache_is_true` !

**Comment by Sparrow0hawk** [comment]
I'll take a look at this. Enjoy the circular nature of the problem though as shown by the bot above!
