### ISSUE TITLE
No lockdown not working

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#168]
Hi @nickmalleson running into an issue when trying to ignore lockdown effects. I used an empty string for the lockdown parameter in the default.yml parameters file but it still seems to call the 'google_mobility_lockdown_daily.csv'.

Can take look into it but thought it would be good to flag.

**Comment by nickmalleson** [comment]
Ah, you might have stumbled on a nice bug. Could you try running it with `--no-use-cache`? I think that the problem may be that if the model can reload itself from the cache then changes to some of the parameters (like the lockdown file) are being ignored.

**Comment by nickmalleson** [comment]
Sorry, just to be clear, run it with something like `python microsim/main.py --no-use-cache`

**Comment by spoonerf** [comment]
Oo okay tried the no cache flag but ran into this issue:

```
Traceback (most recent call last):
  File "microsim/main.py", line 300, in <module>
    main()
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/main.py", line 186, in main
    cache.store_in_cache(individuals, activity_locations, time_activity_multiplier)
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/initialisation_cache.py", line 22, in store_in_cache
    time_activity_multiplier.to_pickle(self.time_activity_multiplier_filepath)
AttributeError: 'NoneType' object has no attribute 'to_pickle'
```

**Comment by nickmalleson** [comment]
Ah OK, let me experiment. Could create the exact setup you're using as a (new?) branch so that I can try to recreate this?

**Comment by nickmalleson** [comment]
If you're keen on typing you could use 'spoonerf-issue-168-No_lockdown_not_working' that the bot helpfully created for you :-)

**Comment by spoonerf** [comment]
Sure - one mo! Well it would be rude not to use that one :)

**Comment by spoonerf** [comment]
@nickmalleson should be up to date now - I used 

```
python microsim/main.py -p ./model_parameters/no_lockdown.yml --no-use-cache

```
and got the above error. 

Trying with deleting the cached .pkls now so will let you know how that goes!

**Comment by spoonerf** [comment]
Is it perhaps trying to pickle something that doesn't exist when using the --no-use-cache flag? Would a solution would be to have a no lockdown csv where the multiplier is 1 every day?

**Comment by nickmalleson** [comment]
Don't worry I have a plan, give me 10 mins

**Comment by nickmalleson** [comment]
OK I've just pushed some changes to that branch (https://github.com/Urban-Analytics/RAMP-UA/tree/spoonerf-issue-168-No_lockdown_not_working) which should have fixed the problem. The main one is https://github.com/Urban-Analytics/RAMP-UA/commit/e59cca9dac4800ce048e3a0241a4d2334f7cb12f . Basically now it reads the lockdown file separately from the other population files. So it will still cache the population, but will re-read the lockdown file every time you run the model. This also means that if there is no lockdown file then the `time_activity_multiplier` variable will be set to `None` and no lockdown will happen Basically give it a try it should work, regardless of whether you use the `--no-use-cache` flag or not.

You can also delete the file `devon_data/caches/time_activity_multiplier.pkl` as it isn't used any more, but it shouldn't break anything to have it there.

**Comment by spoonerf** [comment]
Great will try it out now!

**Comment by spoonerf** [comment]
Success! Thanks @nickmalleson 🎉
