### ISSUE TITLE
submodules not found by setup.py

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#182]
Setuptools isn't correctly finding submodule packages in microsim when we run `python setup.py install`

Setup.py should find submodules thanks to `setuptools.find_packages()` however this doesn't seem to have worked for any submodules without an `__init__.py`. Now, whilst strictly speaking from [PEP 420](https://www.python.org/dev/peps/pep-0420/) you don't need to have an `__init__.py` in every submodules I think the `setuptools.find_packages()` function doesn't correctly find all submodules without them.

Therefore, i'm going to create a quick branch that adds them in, check everything works before merging.

**Comment by Sparrow0hawk** [comment]
@rory-improbable @cshenton 

Do you guys forsee any potential problems for me adding these `__init__.py` files into the opencl stuff?

**Comment by rory-improbable** [comment]
@Sparrow0hawk I don't see why that would be a problem, I say go ahead!
