### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'glGetError'

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#197]
I'm trying to run the OpenCL version using the notebook here: https://github.com/Urban-Analytics/RAMP-UA/blob/master/experiments/sensitivity_analysis/sensitivity_analysis.ipynb It works fine on my mac, but I'm now trying it in an Ubuntu azure virtual machine and am getting the error below. Anything obvious I should try? My sense is that this is a problem with OpenCL drivers on Ubuntu. I've not tried to debug it at all, so if nothing obvious springs to mind I'll dig further.

```
Traceback (most recent call last):
  File "experiments/experiments_functions.py", line 14, in <module>
    from microsim.opencl.ramp.run import run_headless
  File "/home/nick/RAMP-UA/microsim/opencl/ramp/run.py", line 6, in <module>
    from microsim.opencl.ramp.inspector import Inspector
  File "/home/nick/RAMP-UA/microsim/opencl/ramp/inspector.py", line 7, in <module>
    from imgui.integrations.glfw import GlfwRenderer
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/imgui/integrations/glfw.py", line 8, in <module>
    from .opengl import ProgrammablePipelineRenderer
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/imgui/integrations/opengl.py", line 4, in <module>
    import OpenGL.GL as gl
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by rory-improbable** [comment]
@nickmalleson this looks like an OpenGL error, so it's possible that the right drivers for OpenGL aren't installed.

However OpenGL is only used for the UI, and presumably if you're running on Azure you mainly care about running the model in headless mode and don't need the UI? If that is the case then as a short term fix you could comment out importing the Inspector, and any code which references the inspector (so presumably just the `run_with_gui` function in `run.py`). Then the model should run fine in headless mode (fingers crossed).

Additionally I can have a look into this to see what the problem is, it might be an issue on other Ubuntu machines so worth getting to the bottom of it. 

Do you know what version of Ubuntu is being used?

**Comment by rory-improbable** [comment]
Also I just did some quick googling and this is a potential fix, if you can run the following:
```
sudo apt-get install python3-opengl
```

**Comment by nickmalleson** [comment]
Thanks Rory, commenting out the `Inspector` inport from here:
https://github.com/Urban-Analytics/RAMP-UA/blob/ecb49a89b1b5da878dda5897d71aba631d5e36e4/microsim/opencl/ramp/run.py#L6
worked fine. I'll close this now. As an aside, maybe that import line could be moved to here:
https://github.com/Urban-Analytics/RAMP-UA/blob/ecb49a89b1b5da878dda5897d71aba631d5e36e4/microsim/opencl/ramp/run.py#L28
so the `Inspector` libraries is only imported if the GUI is needed. Maybe it's bad practice though to put import lines wihin the main code? Anyway I'll leave it for now as the workaround is fine.

As it's OK now I didn't try instaling the opengl libraries, as you say I only need it in headless mode.

**Comment by rory-improbable** [comment]
@nickmalleson my personal preference is to keep imports at the top of files, however I'm not sure whether that is standard practice or just my own bias. 

To be honest possibly the best solution would be to move the `run_with_gui` function to a separate file that has different imports. But in this case I'm happy with just moving the import Inspector line  into the `run_with_gui` function, I think that's a decent fix here.
