### ISSUE TITLE
Documentation for creation of observations file

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#207]
Hi @spoonerf , is there somewhere where the observations are documented properly? I had a quick go at this here:

https://github.com/Urban-Analytics/RAMP-UA/tree/master/experiments/sensitivity_analysis/observation_data

(note that that uses the old gam_cases file though). Do you have somewhere where the observations and associated scripts are documented? If not shall I just tidy up the contents of the directory above and put it somwhere more accessible?

**Comment by spoonerf** [comment]
hi @nickmalleson ah no they weren't documented anywhere properly, what you've done looks great! Just a small change to the R script which I'll do a PR for now. The original script essentially ignores the initial 10 cases. The new script will align with the gam_cases file we are using now.

**Comment by nickmalleson** [comment]
Brilliant, thanks Fiona. Merged https://github.com/Urban-Analytics/RAMP-UA/pull/208
