### ISSUE TITLE
OpenCL: `kernel 'x' was part of a lengthy source build resulting from a binary cache miss`

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#211]
I'm using an ABC library to sample from the model, but am getting these info messages:

```
INFO:pyopencl:build program: kernel 'places_reset' was part of a lengthy source build resulting from a binary cache miss (0.24 s)
INFO:pyopencl:build program: kernel 'people_update_flows' was part of a lengthy source build resulting from a binary cache miss (0.24 s)
INFO:pyopencl:build program: kernel 'people_send_hazards' was part of a lengthy source build resulting from a binary cache miss (0.24 s)
INFO:pyopencl:build program: kernel 'people_recv_hazards' was part of a lengthy source build resulting from a binary cache miss (0.24 s)
INFO:pyopencl:build program: kernel 'people_update_statuses' was part of a lengthy source build resulting from a binary cache miss (0.24 s)
```

The model seems to be working fine so I am happy to ignore them. Is it something I should be concerned about? Also is it possible to surpress  these messages? (only because they will fill up my notebook with junk if I take a lot of samples)

**Comment by cshenton** [comment]
I've done a quick search and these messages are from pyopencl, not the underlying opencl compiler, so you will be able to disable them. To make it so that only ERROR logs show up the following _should_ work (so long as you run this after the pyopencl import). 

```python
import logging
logging.getLogger("pyopencl").setLevel(logging.ERROR)
```

Alternatively `logging.WARNING` if you still want to see warning logs.

**Comment by nickmalleson** [comment]
Perfect, thanks @cshenton . FYI the messages aren't printed when I run this on the Azure Ubuntu VM (I use OS X at home)
