### ISSUE TITLE
Google mobility lockdown multiplier changes with increases in data

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#220]
Hi all, I was just working on documenting the google mobility lockdown multiplier and realised a small bug. We use a GAM to smooth the google mobility data in order to get a smoothed estimate of the proportional decrease in the amount of time spent outside the home. However when new data is added to this the predicted values of the GAM shift a bit meaning that the multiplier would change slightly every time new data is added.

A work around for this is to not smooth it, the only reason we were initially (that I can remember) was to try and get a smooth effect of lockdown on the cases, which I don't think is so important any more now we know the model works. It means we would definitely have more of a weekend effect of people being out and about more.

Image shows a comparison of the 'raw' google mobility lockdown multiplier in black with the smoothed multiplier in red.

![image](https://user-images.githubusercontent.com/10774728/99528195-d7a96180-2995-11eb-8860-f6996bb7b23c.png)

What do you guys think?

**Comment by spoonerf** [comment]
R code used to create above plot
`
library(readr)
library(tidyr)
library(ggplot2)
library(mgcv)

###downloading latest file from google mobility
download.file("https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv", 
              destfile = "Google_Global_Mobility_Report.csv")

gm <- read_csv("Google_Global_Mobility_Report.csv") %>% 
  filter(country_region == "United Kingdom" & sub_region_1 == "Devon" & iso_3166_2_code == "GB-DEV") %>% 
  dplyr::select( -c(country_region_code,  sub_region_2)) %>% 
  pivot_longer(., contains("percent"))

residential_pcnt <- gm %>% 
  mutate(day = as.numeric(date) - 18306) %>%
  filter(name == "residential_percent_change_from_baseline" & day < 201) 

rv <- (residential_pcnt$value/100) + 1
dates <- seq(min(gm$date), min(gm$date) + length(rv)-1, 1)

smooth_residential <- mgcv::gam(value ~ s(day, bs = "cr"), data = residential_pcnt)
sr <- fitted.values(smooth_residential)
sr <- (sr/100) + 1

phome <- 0.7573431 #proportion of time the average Devon citizen spends at home.
pnothome <- 0.2426569 #proportion of time the average Devon citizen spends outside home.

new_out_sm <- 1 - (phome * sr) 
new_out <- 1 - (phome * rv) 

lock_down_reducer_sm <-  new_out_sm/pnothome

lock_down_reducer_rv <-  new_out/pnothome


plot(dates, lock_down_reducer_rv, ylab = "Proportion of Time Outside Compared to Baseline", type = "l", xlab = "Day")
lines(dates,lock_down_reducer_sm, col = "red")

`

**Comment by spoonerf** [comment]
Will try the model out with the unsmoothed values after lunch!

**Comment by spoonerf** [comment]
About a third fewer infections when using the unsmoothed values - probably something we need to decide on @nickmalleson

**Comment by nickmalleson** [comment]
Intuitively I prefer the smoothed version because we don't have an explicit weekday/weekend differentiation in the model. I don't fully understand the bug; is there a way to fix it so that it doesn't 'shift'?

**Comment by spoonerf** [comment]
Hmm will ask Gavin if there's a clever way of doing that, but failing that could use a moving average?

14 day moving average shown in blue:

![image](https://user-images.githubusercontent.com/10774728/99647996-6d062d80-2a4a-11eb-917a-aa52d9581f9b.png)

**Comment by nickmalleson** [comment]
The moving average looks good. I think it's more robust than the big jumps

**Comment by spoonerf** [comment]
Okay brill, I will upload the moving average one and script to go with it in a PR shortly. Charlie suggested making a more generalisable function which I think is a good idea, but I'm also conscious that I should stop changing things whilst you are calibrating! So think it might be best to stick with the moving average for now and then explore a more general option for when we expand out of Devon?

**Comment by nickmalleson** [comment]
@spoonerf .. bit late now, but don't worry if you need to change things that will affect the calibration. I just re-run the script. Onlyl thing to be aware of is that I'm using the OpenCL version for calibration, so if your change only impacts on the python version then it wont affect the work I'm doing

**Comment by spoonerf** [comment]
Okay cool - have done a PR to switch things to the 14 day moving average for google mobility for now. This will affect both the R/Python and the OpenCL models, but I don't think will impact the outputs much.

**Comment by nickmalleson** [comment]
I think this was completed in https://github.com/Urban-Analytics/RAMP-UA/pull/222 . Closing.
