### ISSUE TITLE
Clean up non-quant code

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#255]
Remove the old code that creates bespoke devon school and retail SIMs.

**Comment by ciupava** [comment]
Hi @nickmalleson, regarding this issue, it is maybe worth mentioning my comment to @spoonerf's question (which was wrong there but can be pertinent here).
https://github.com/Urban-Analytics/RAMP-UA/pull/241#issuecomment-778125298
In my case, I was trying to play around with the `quant_object` variable somewhere else, while running the tests, but setting it to `False` would enter in these two `If` condition within `population_initialisation.py` and not run the test:
https://github.com/Urban-Analytics/RAMP-UA/blob/9b3a7c48a27cb942768f709fd3391bcce570d242/microsim/population_initialisation.py#L569
and
https://github.com/Urban-Analytics/RAMP-UA/blob/9b3a7c48a27cb942768f709fd3391bcce570d242/microsim/population_initialisation.py#L844
I am sorry I don't remember much more about this now, but can maybe try to reproduce the same situation where I was. In any case just wanted to point out that the tests might be affected by this change of the code. Thanks for raising the issue!

**Comment by nickmalleson** [comment]
Thanks @ciupava , I think I found the places that you mention. This should be OK now because there are no checks to see if the `quant_data` object is `False`, now we always assume that it is a pointer to a `QuantRampAPI` object.

I think I have gotten this to work and am just ironing out some of the tests. In the meantime some things to note:
 - The directory `devon_data/QUANT_RAMP` is hard-coded into some of the tests. This can be replaced with the common data directory once the new code structure is in place. I did it this way rather than storing the RAMP data with the other test data because it will mean duplication of data. (Previously I made some small csv files to represent a hypothetical 'devon' for the tests, but can't easily see a way to do this for the Quant API).
 - The tests are quite slow now as the Quant object needs to be initiialised. @Sparrow0hawk do you know if there a way to initialise the `QuantRampAPI` object and then share that instance across different test files? E.g. the following lines are repeated in `test_microsim_model.py`, `test_population_initialisation.py` and `opencl/test_update_flows_kernel.py`:
 
 ```
 population_init_args = {...
                        "quant_object": QuantRampAPI(os.path.join("devon_data", "QUANT_RAMP"))
                        }
```

Finally, the following isn't important, I only mention it so there is a record somewhere. I have renamed some of the arbitrary areas in the test data (the individual population file and the commuting flows file). This is because the old area codes did not feature in the quant data (I'm not sure what they were to be honest). The new areas have been renamed as follows:

E00101308 -> E02004297
E02004158 -> E02004290
E02004151 -> E02004298
E02004159 -> E02004299
E02004142 -> E02004291
E02004132 -> E02004300
E02004147 -> E02004292
E02004138 -> E02004301

**Comment by nickmalleson** [comment]
Being dealt with in https://github.com/Urban-Analytics/RAMP-UA/pull/263
