### ISSUE TITLE
QUANTRampAPI2.py v  quant_api.py 

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#268]
I'm nit picking through things on documentation and have noticed we have both [QUANTRampAPI2.py](https://github.com/Urban-Analytics/RAMP-UA/blob/master/microsim/QUANTRampAPI2.py) and [quant_api.py](https://github.com/Urban-Analytics/RAMP-UA/blob/master/microsim/quant_api.py).

They both lack tests but also seem broadly to do similar things with `quant_api.py` simply being a more standard python module.

@nickmalleson are we able to tidy this up and remove QUANTRampAPI2.py from microsim module?

**Comment by ciupava** [comment]
I don't think that QuantRampAPI2 is actually used.

**Comment by nickmalleson** [comment]
Indeed, `QuantRampAPI2` is a hangover from some old code that Natalie was writing. I have deleted it as part of issue https://github.com/Urban-Analytics/RAMP-UA/issues/267 (in commit d769ee1) . We should write tests for quant_api.py, this is the subject of https://github.com/Urban-Analytics/RAMP-UA/issues/262
