### ISSUE TITLE
OpenCL tests failing (probably a seeding issue)

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#289]
Sorry @rory-improbable , I've come up against another bug. But I think this is an easy one to resolve. I am working on a branch that @spoonerf was using to implement the experiments that she ran for the paper. The only test that fails is `test_seed_initial_infections_some_low_risk()`.

The offending line is:

https://github.com/Urban-Analytics/RAMP-UA/blob/fff3b9247d35f494817a75b6e3da762b20c9db17/tests/opencl/test_update_statuses_kernel.py#L632

The `people_statuses_before` array should be full of zeros, but it looks like one person has an infection. This is the value of the array when I debug the tests:

```
people_statuses_before
Out[6]: 
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=uint32)
```

As an aside, if I just run this test on it's own then it passes. The problem occurs when I run all the tests together. So I _think_ that maybe something is being set in another test that is causing someone to be infected? 

While you're looking at that one, please could you also look a few lines further down as I think this line will need changing:

https://github.com/Urban-Analytics/RAMP-UA/blob/fff3b9247d35f494817a75b6e3da762b20c9db17/tests/opencl/test_update_statuses_kernel.py#L640

We have updated the initial cases file, so I will need to change the `3`, but I am not sure where the value of `3` came from. Here is the original data file in the master branch, if you can tell me which row of the data the test refers to I can fix it:

https://github.com/Urban-Analytics/RAMP-UA/blob/master/microsim/opencl/data/devon_initial_cases.csv

Thanks!

**Comment by rory-improbable** [comment]
PR for fix here: https://github.com/Urban-Analytics/RAMP-UA/pull/294
