### ISSUE TITLE
Add `pygam` and `pyabc` to environment

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#290]
They are required to run some of the calibration and data assimilation routines

**Comment by nickmalleson** [comment]
@Sparrow0hawk the `pyabc` library seems to only be avaialble using `pip`, not `anaconda`.

E.g. the [docs](https://pyabc.readthedocs.io/en/latest/installation.html) recommend installing with 

```
pip install pyabc
```

Do you know how to add this to the environment file?

I have alread added `pygam` to the file on the [nickmalleson-issue-290](https://github.com/Urban-Analytics/RAMP-UA/tree/nickmalleson-issue-290) branch: https://github.com/Urban-Analytics/RAMP-UA/blob/nickmalleson-issue-290/environment.yml

**Comment by Sparrow0hawk** [comment]
Do we think these packages are essential for the model to run? I'm sort of a mind that if these packages are not necessary but rather optional to help perform calibration/experiments it would be better to not include them explicitly in the environment but rather to include documentation about installing those packages in the notebook where you're doing calibration experiments.

What do you think and does that make sense?

**Comment by nickmalleson** [comment]
Actually yes I agree with you. Better to stop the environment becoming too bloated.
