### ISSUE TITLE
Document problem with janitor library

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#39]
It's an R library we need. But can't be installed with the  rest through `conda install r-janitor`. So needs to be installed manually using R `install.packages('janotor')`

**Comment by nnelissen** [comment]
It's also on conda-forge `conda install -c conda-forge r-janitor`

**Comment by nickmalleson** [comment]
Oh yeah! thanks, I just included that and updated the environment file https://github.com/Urban-Analytics/RAMP-UA/commit/747c6cf17d66c421e98fbef371f0e12c52b01722
