### ISSUE TITLE
test_analysis.py file in tests/

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#59]
In the PR #56 I moved the file `test_analysis.py` into the tests/ directory.

This is the consistent cause of the test suite failing so i'm going to create an issue on this to keep track of what we're doing about it.

I've tagged in @nickmalleson and @nnelissen as i'd like your input on whether this file is a test file (and so we can update it to pass) or if its an artefact of when you were informally testing stuff (and so it can be removed from the repo).

**Comment by nnelissen** [comment]
Let's remove it, it was misnamed and not a proper test. I'll work on an actual test file for the dashboard

**Comment by Sparrow0hawk** [comment]
Closing this issue as resolved in 6b3c24f9a386edbdcee56ab3257fcf6787de17ee
