### ISSUE TITLE
Microsim test failure on Windows : test_random

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#75]
## Problem and stacktrace
Tests start to run but now fail on [`test_random`](https://github.com/Urban-Analytics/RAMP-UA/blob/48576dc7aa076489c72cfdfbd609c0f81a59ab47/tests/test_microsim_model.py#L411). Something i'll create a new issue for.

> def test_random():
>         """
>         Checks that random classes are produce different (or the same!) numbers when they should do
>         :return:
>         """
>         m1 = Microsim(**microsim_args, read_data=False)
>         m2 = Microsim(**microsim_args, random_seed=2.0, read_data=False)
>         m3 = Microsim(**microsim_args, random_seed=2.0, read_data=False)
>     
>         # Genrate a random number from each model. The second two numbers should be the same
>         r1, r2, r3 = [_get_rand(x) for x in [m1, m2, m3]]
>     
>         assert r1 != r2
>         assert r2 == r3
>     
>         # Check that this still happens even if they are executed in pools.
>         # Create a large number of microsims and check that all random numbers are unique
>         pool = multiprocessing.Pool()
>         m = [Microsim(**microsim_args, read_data=False) for _ in range(10000)]
>         r = pool.map(_get_rand, m)
> >       assert len(r) == len(set(r))
> E       assert 10000 == 409
> E        +  where 10000 = len([0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, ...])
> E        +  and   409 = len({0.0004759783146218721, 0.0010528736536226102, 0.008873069293537483, 0.009529687314436819, 0.011380324399635655, 0.012347288919539401, ...})
> E        +    where {0.0004759783146218721, 0.0010528736536226102, 0.008873069293537483, 0.009529687314436819, 0.011380324399635655, 0.012347288919539401, ...} = set([0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, 0.008873069293537483, ...])

## Steps to reproduce

On Windows 10 with git bash:
```bash
conda activate ramp-ua
pytest
```

Reproduced within GitHub actions Windows test runner (https://github.com/Urban-Analytics/RAMP-UA/actions/runs/189880378)

**Comment by Sparrow0hawk** [comment]
Looks like this behaviour still occurs on windows test suite. Looks like its maybe more complex than initially thought and to do with how `random` is interacting with `pool.map`

I'd suggest changing [this line in Microsim.random](https://github.com/Urban-Analytics/RAMP-UA/blob/715bd2fde722afb6c13cb5cacf74e253945f78d0/microsim/microsim_model.py#L104). 

Currently the behaviour is to use system time if random_seed is None. I think with pooled processes this seems on Windows to lead to multiple randoms using the same seed. If we let `random.random` work on its default behaviour it'll use OS specific randomness sources as the seed which should prevent this error.

Commit incoming.

**Comment by nickmalleson** [comment]
Sorry I got confused and also tried to fix this. We basically did the same thing.
