### ISSUE TITLE
Tidy up of R/py_int and adding some tests or moving things to functions or rampuaR

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#78]
The `R/py_int` directory has alot going on in it and from as far as I can tell the most important bits are `output/` and `covid_run.R`.

It'd be great if we could do the following:
- [x] - go through files listed below that exist in that directory and determine if they're in the right place/can de removed/moved
- [x] - break up `run_status` as much as possible into smaller functions with tests so we can better try and isolate problems

Files to decide on:
- `covid_run_py.R`
- `.Rhistory` (unless this has something super important in there we should remove this)
- `covid_status_functions.R` - is this now in `rampuaR`?
- `devon_cases.RDS` - if this is essential we should move it to a data directory
- `gam_fitted_PHE_cases.RDS` - same as above
- `google_mobility_all_LAD.R` - is this now in `rampuaR`?
- `initialize_and_helper_functions.R` - is this now in `rampuaR`?
- `lockdown_multiplier.R` - is this now in `rampuaR`?
- `msoa_danger_fn.csv` - same as RDS files above
- `plotting_new_cases.R` - is this now in `rampuaR`?

Thoughts welcome!

**Comment by spoonerf** [comment]
Hi Alex,

In terms of the files:

covid_run_py.R - I think is old and not needed any more, right @jabrams23 ?
.Rhistory - I think just auto-added by R but will add to the .gitignore and remove
covid_status_functions.R - This is in rampuaR
devon_cases.RDS - can be deleted
gam_fitted_PHE_cases.RDS - is in the data part of rampuaR (on the wrapper branch) but will need to be called slightly differently now
google_mobility_all_LAD.R - is in rampuaR
initialize_and_helper_functions.R - is in rampuaR
lockdown_multiplier.R - is in rampuaR
msoa_danger_fn.csv - same as gam_fitted_PHE_cases.RDS
plotting_new_cases.R - not in rampuaR but can be added, just some basic data viz.

Will do a clean-up this morning and change how gam_fitted_PHE_cases.RDS and msoa_danger_fn.csv are called in covid_run.R

**Comment by Sparrow0hawk** [comment]
Hi @spoonerf 

`.Rhistory` is typically autoadded by R, it just preserves all commands that are ever typed into the R console during an R session. Much appreciated for tidying this up!

**Comment by spoonerf** [comment]
@Sparrow0hawk Ah okay brilliant - have done a bit of a tidy up and a pull request for this.

**Comment by jabrams23** [comment]
@Sparrow0hawk with respect to breaking the run_status function down...this is essentially just a function that calls smaller functions. so it is the pipeline to run the model calling the functions from the r package. im not sure how much more we could break it down

**Comment by jabrams23** [comment]
#92 i did some work on that here

**Comment by Sparrow0hawk** [comment]
Closing this as quite old and previously resolved.
