### ISSUE TITLE
AssertionError in covid_run.R on Windows

### ISSUE THREAD

**Issue by Sparrow0hawk** [Urban-Analytics/RAMP-UA#79]
## Issue and stacktrace

```
$ python microsim/microsim_model.py
C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\rpy2\robjects\pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed i
n a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
Reading parameters file: ./model_parameters/default.yml. Any other command-line arguments are being ignored
Running model with the following parameters:
        Parameters file: ./model_parameters/default.yml
        Number of iterations: 10
        Data dir: devon_data
        Outputting results?: True
        Debug mode?: False
        Number of repetitions: 1
        Lockdown from file? : True
        Calibration parameters: {'hazard_multiplier_presymptomatic': 1.0, 'hazard_multiplier_asymptomatic': 1.0, 'hazard_multiplier_symptomatic': 1.0, 'risk_multiplier': 1.0}

Reading time use and health data ...
microsim/microsim_model.py:440: UserWarning: There are 6 / 695308 non-unique individuals.
  warnings.warn(f"There are {len(tuh)-len(set(unique_individuals))} / {len(tuh)} non-unique individuals.")
microsim/microsim_model.py:489: UserWarning: 32 people > 18y/o go to school, but they are not being assigned to a primary or secondary school (so their schooling is ignored at the mo
ment
  warnings.warn(f"{len(adults_in_school)} people > 18y/o go to school, but they are not being assigned to a "
microsim/microsim_model.py:500: UserWarning: There are 0 households with more than 10 people in them. This covers 0 people. These households are being removed.
  warnings.warn(f"There are {len(large_house_idx)} households with more than 10 people in them. This covers "
... finished reading TU&H data. There are 695308 individuals in 346343 houses over 107 MSOAs
Reading retail flow data for Devon...
... read 106990.0 flows from 107 areas.
Assigning individual flows for Retail: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:05<00:00, 20.01it/s]
Reading school flow data for Devon...
... finished reading school flows.
Assigning individual flows for PrimarySchool: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:05<00:00, 18.29it/s]
Assigning individual flows for SecondarySchool: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:07<00:00, 14.87it/s]
Assigning work venues ...
C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\rpy2\robjects\pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed i
n a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\rpy2\robjects\pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed i
n a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\rpy2\robjects\pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed i
n a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\rpy2\robjects\pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed i
n a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
Rounding all durations: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.72it/s]
Reading time activity multiplier data...
 ... finished initialisation.
Saving initial models for analysis ...
Initialising R interface. Loading R scripts in C:\Users\medacola\Code\forks\RAMP-UA\R\py_int.
package is up-to-date devel version

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Iteration: 1

        Applying regular (google mobility) multiplier 0.9305173110479441
        Updating danger associated with visiting each venue
                Home activity
                Retail activity
                PrimarySchool activity
                SecondarySchool activity
                Work activity
        Calculating new disease status...[1] "R timestep: 1"
[1] "First day seeded"
[1] "0 individuals with risk above  5"
[1] "betas calculated"
[1] "probabilities calculated"
[1] "cases assigned"
[1] "PHE cases 10"
[1] "model cases 0"
[1] "Adjusted PHE cases 10"
[1] "w is 0"
[1] "infection and recovery lengths assigned"
[1] "individuals removed"
[1] "updating infection lengths"
Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1619, in <module>
  File "C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\medacola\AppData\Local\Continuum\anaconda3\envs\ramp-ua\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1595, in run_script
  File "microsim/microsim_model.py", line 1452, in run
  File "microsim/microsim_model.py", line 1433, in step
  File "microsim/microsim_model.py", line 1306, in calculate_new_disease_status
  File "C:\Users\medacola\Code\forks\RAMP-UA\microsim\r_interface.py", line 62, in calculate_disease_status
    assert len(r_df) == len(individuals)
AssertionError
```

## Steps to reproduce

Windows 10, within ramp-ua conda environment, calling `microsim/microsim_model.py`

**Comment by nnelissen** [comment]
I just got the same error on Ubuntu (latest version master + updated ramp-ua env)

Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1686, in <module>
    run_script()
  File "/home/natalie/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/natalie/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/natalie/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/natalie/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1662, in run_script
    m.run(iterations)
  File "microsim/microsim_model.py", line 1519, in run
    self.step()
  File "microsim/microsim_model.py", line 1500, in step
    self.calculate_new_disease_status()
  File "microsim/microsim_model.py", line 1373, in calculate_new_disease_status
    self.individuals = self.r_int.calculate_disease_status(self.individuals, self.iteration)
  File "/home/natalie/Documents/RAMP-UA/microsim/r_interface.py", line 62, in calculate_disease_status
    assert len(r_df) == len(individuals)
AssertionError

**Comment by jabrams23** [comment]
also getting the same error on mac

**Comment by jabrams23** [comment]
@spoonerf are you also getting this error? I cant test any changes that i have made because i keep getting this assertion error

**Comment by spoonerf** [comment]
@jabrams23 Nope I'm not - everything working fine for me

**Comment by jabrams23** [comment]
thought id include the full error code. I am using latest version of master and ramp-ua environment installed today on MacOS

Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1627, in <module>
    run_script()
  File "/Users/jesse/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jesse/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jesse/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jesse/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1603, in run_script
    m.run(iterations)
  File "microsim/microsim_model.py", line 1453, in run
    self.step()
  File "microsim/microsim_model.py", line 1434, in step
    self.calculate_new_disease_status()
  File "microsim/microsim_model.py", line 1307, in calculate_new_disease_status
    self.individuals = self.r_int.calculate_disease_status(self.individuals, self.iteration, self.disease_params)
  File "/Users/jesse/Documents/GitHub/RAMP-UA/microsim/r_interface.py", line 63, in calculate_disease_status
    assert len(r_df) == len(individuals)
AssertionError

**Comment by Sparrow0hawk** [comment]
Thanks @jabrams23 the same as others have seen, i'm working on this now as its a key bottleneck.

Initially it looks like the output from `run_status` is not the same length as the initial dataframe of individuals passed. Were there any changed in `rampuaR` that drop rows?

**Comment by jabrams23** [comment]
Not that I’m aware of.

**Comment by Sparrow0hawk** [comment]
So I think the predominant issue here is that the assertion this fails: https://github.com/Urban-Analytics/RAMP-UA/blob/ea0887a4894ddcd68bfd71418a744dc2bea598a9/microsim/r_interface.py#L61

Is because dataframe passed to the r_interface is actually a subset of the columns within the full individuals dataset:
https://github.com/Urban-Analytics/RAMP-UA/blob/ea0887a4894ddcd68bfd71418a744dc2bea598a9/microsim/r_interface.py#L59

Because we only pass a partial subset of the original dataframe to this function it will always fail this assertion.

I think a solution here is to remove this assertion and write some tests for the r_interface that can perform this sort of check. This goes alongside the issues in #95 about ensuring we update our test dataset so it is similar to current model inputs. 

Thoughts @nickmalleson

**Comment by nickmalleson** [comment]
@Sparrow0hawk I'm not sure that's right. `len` on a dataframe gives you the number of rows, not the number of columns (to get the number of columns you do `len(r_df.columns)`. So if the assertion (https://github.com/Urban-Analytics/RAMP-UA/blob/ea0887a4894ddcd68bfd71418a744dc2bea598a9/microsim/r_interface.py#L59) is failing that's because the number of rows returned from the R code is different to the number of rows in the original data frame. 

You could make a slightly more verbose assertion which might help to debug, e.g. something like:

```
assert len(r_df) == len(individuals), f"The number of rows in the original data frame ({len(individuals)}) is not the same as the one returned from R ({len(r_df)})"
```
```

**Comment by jabrams23** [comment]
not sure why its failing...im still getting it so I added code to have the r function print out the nrows of the data frame and I am getting 695309 as expected. so something else is going wrong

**Comment by jabrams23** [comment]
i just added some more print statements. 

when i do print(nrow(r_df)) in r I get 695309

in python when i do print(len(individuals)) i get 695309
but in python when i do print(len(r_df)) i get 7...this is returning the nubmer of columns and not rows

**Comment by nickmalleson** [comment]
Thats interesting, I'll have a look too. Are you using the code on the master branch?

--
Sent from a mobile, sorry about the grammar

________________________________

**Comment by jabrams23** [comment]
Yep I just pulled from the master branch about 30 minutes ago

**Comment by jabrams23** [comment]
Seems like the r2py is returning the transposition of the data frame from R somehow

**Comment by jabrams23** [comment]
Trying print(len(r_df.columns)) returns:
AttributeError: 'DataFrame' object has no attribute 'columns'

so it seems like something isnt working properly when passing the dataframe from r to python

**Comment by nickmalleson** [comment]
I'm going to debug further now but (a) it works for me! and (b) it sounds like for you the object being returned from R is not being converted into a pandas DataFrame (the library I'm using to run the R from python should convert between R and Python DataFrames by default - something it has been doing correctly until now.

**Comment by jabrams23** [comment]
did a bit more detective work

print(r_df.size) returns AttributeError: 'DataFrame' object has no attribute 'size'
print(r_df.shape) returns AttributeError: 'DataFrame' object has no attribute 'shape'
print(r_df.ndim) returns AttributeError: 'DataFrame' object has no attribute 'ndim'

so definitely something wrong with what is being passed from r to python even though the dataframe in the r script that is being returned is correct.

i think the problem may be that what is returned from r to python is not a pandas dataframe but an rpy2.robjects.vectors.DataFrame

the dataframe needs to be converted to a pandas dataframe see: https://rpy2.github.io/doc/latest/html/pandas.html

**Comment by jabrams23** [comment]
> I'm going to debug further now but (a) it works for me! and (b) it sounds like for you the object being returned from R is not being converted into a pandas DataFrame (the library I'm using to run the R from python should convert between R and Python DataFrames by default - something it has been doing correctly until now.

when did you last install the environment? i did it today. maybe something has changed in the rpy2 package?

**Comment by nickmalleson** [comment]
Definitely works for me. Very odd that it isn't working for you now. Here's what I get:
```ipython
type(individuals_reduced)
Out[6]: pandas.core.frame.DataFrame

len(individuals_reduced)
Out[2]: 695309

# Now call the run_status function: r_df = self.R.run_status(individuals_reduced, iteration, **disease_params)

type(r_df)
Out[4]: pandas.core.frame.DataFrame

len(r_df)
Out[5]: 695309
```

I'm currently writing a test to check that R and Python are behaving as they should. I'm expecting it to work on my machine so it will be interesting to see if it works on others.

@spoonerf does the code on the latest version of master work for you?

**Comment by jabrams23** [comment]
I think it must be something to do with Conda updating the version of rpy2 that is there. An rpy2 data frame is being returned and not a pandas one for me.

Did you update the environment? Check that maybe it will start throwing the same error?

**Comment by jabrams23** [comment]
@nickmalleson which version of rpy2 is installed in your environment? i have 2.9.4

**Comment by spoonerf** [comment]
@nickmalleson yep all working for me - haven't had the assertion error at any stage

**Comment by spoonerf** [comment]
@nickmalleson Just updated to the most recent environment.yml and now I do get the error!

**Comment by jabrams23** [comment]
@nickmalleson try updating i bet youll get the error. when teh code starts running i get a warning message:

/Users/jesse/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex

looks like something with pandas has changed

**Comment by nickmalleson** [comment]
Yeah OK I think you’re both right, it looks like they have changed the behaviour in rpy2 and/or pandas and no longer do the same implicit conversion to the pandas DataFrame.

I don’t want to try to work out what’s changed now, or how to fix it. Can you both revert to the previous versions? Here is the versions that I have that are working (and how to find out which versions you're using from the command line):

```
(ramp-ua) Mac-Pro:RAMP-UA nick$ conda list pandas
pandas                    1.0.3            py37h6c726b0_0  

(ramp-ua) Mac-Pro:RAMP-UA nick$ conda list rpy2
rpy2                      3.3.2           py37r36h10e2902_0    conda-forge
```

You can install the specific versions using this command:

```
conda install -c conda-forge rpy2=3.3.2 pandas=1.0.3 
```

Hopefully it's as easy as running that command. Let me know if it works and I'll update `environment.yml` so that it forces the install of those versions

**Comment by spoonerf** [comment]
Works when rpy2 is version 3.3.2 and pandas 1.0.3

**Comment by jabrams23** [comment]
i have the same version of pandas but an older version of rpy2. thats the problem! as longa s we update to the more recent version of rpy2 using conda-forge then it works

**Comment by spoonerf** [comment]
I think @Sparrow0hawk rolled back rpy2 because of this problem https://github.com/Urban-Analytics/RAMP-UA/issues/73

**Comment by nickmalleson** [comment]
Ah OK. This is going to get complicated. I just reverted to the newer version in environment.yml (https://github.com/Urban-Analytics/RAMP-UA/commit/84908cacc71bfcdc7fe5f485b7540e9cfa341f77). If it's working for us now lets leave it and look again at the windows problem with @Sparrow0hawk next week.

**Comment by jabrams23** [comment]
working for me now. hopefully we find another way to solve the other problem

**Comment by Sparrow0hawk** [comment]
Good bug hunting everyone!

I'll look for an alternate way to resolve the the run problem on Windows if `rpy2` is the problem. 

I had begun to write some tests for the `r_interface.py` file here https://github.com/Urban-Analytics/RAMP-UA/tree/fix-RassertionError-79 but @nickmalleson have you written some yourself now?

**Comment by nickmalleson** [comment]
> Good bug hunting everyone!
> 
> I'll look for an alternate way to resolve the the run problem on Windows if `rpy2` is the problem.
> 
> I had begun to write some tests for the `r_interface.py` file here https://github.com/Urban-Analytics/RAMP-UA/blob/fix-RassertionError-79/tests/test_r_interface.py but @nickmalleson have you written some yourself now?

Oh nice, they are much more comprehensive than mine (which aren't working anyway). I'll get rid of mine as they're redundant if those tests work.

**Comment by Sparrow0hawk** [comment]
@nickmalleson i'm not sure they work, I was building it yesterday, but as we've resolved the issue around `rpy2` I will get them up to scratch. I'll sort them out on that branch and then offer it to merge in once they're passing

**Comment by Sparrow0hawk** [comment]
Once I have solved tests for the `r_interface.py` and they pass i'm happy for us to close this issue as the update of rpy2 appears to have solved this.

**Comment by jabrams23** [comment]
Can we add a script to run R tests. I have started writing some code for tests for r in the r_tests branch

**Comment by Sparrow0hawk** [comment]
@jabrams23 yes, its on my todo list for this thursday

**Comment by Sparrow0hawk** [comment]
Closing this as a duplicate of #73
