### ISSUE TITLE
Tidy up `microsim_model` directory

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#88]
If there are any old files in `microsim` directory could you get rid of them?

**Comment by nickmalleson** [comment]
I have deleted:
 - microsim/arrays_timeit.py
 - microsim/microsim_initialisation_fs.py (@spoonerf )
 - microsim/microsim_model_JESSE.py (@jabrams23 )
from my branch, let me know if you need to keep them and I'll put them back

**Comment by nnelissen** [comment]
@nickmalleson Yes, microsim_analysis.py is replaced by dashboard.py (though it may be more consistent naming to rename what is now dashboard to microsim_analysis?)

**Comment by spoonerf** [comment]
@nickmalleson All fine with me - delete away!

**Comment by nickmalleson** [comment]
Thanks all. They're still on githiub somewhere so we can get them back if we need to
